### PR TITLE
Update build.yml

### PR DESCRIPTION
**Pull request by science2468**
change to x86-64

### CODE REVIEW

**Comment by ttimasdf** [comment]
Could you further explain the reason of making this change? the ipk package produced is currently platform independent and I personally use it with on a x86 VM as well.

And for the SDK architecture, as the SDK package provided by OpenWrt is a cross compilation toolchain and host architecture is x86 as well. So using any one should be okay and should have no effect on compilation time.

**Comment by science2468** [comment]
Sorry, the author can ignore this commit, I clicked wrong, I didn't mean to submit the patch. I still don't know much about using GitHub features. I changed the platform because I mainly use x86-64 hosting, using GitHub Actions compiled ipk for me to use, the default is the ARM platform, the compiled ipk cannot be used on x86-64 host.

**Comment by ttimasdf** [comment]
你要是编译 xray-core 那确实得分平台，但这个项目编译出来的 ipk 不区分 arch 的，随便哪个 sdk 编译出来都是一样的。举个例子，下面的是我从 x86 的 sdk 编译出来的，文件名带 `_all` 的放到哪里都能装，带 `_x86_64` 的只能在 x86 的机器上装。你可以先试试release里的包，如果还是有问题，可以开个帖子在 [Discussions](https://github.com/ttimasdf/luci-app-xray/discussions/categories/q-a) 里讨论

```
bin/packages/x86_64/base/luci-app-xray_1.23.2-1_all.ipk
bin/packages/x86_64/packages/xray-core_1.6.0-2_x86_64.ipk
bin/packages/x86_64/packages/xray-example_1.6.0-2_all.ipk
```

**Comment by science2468** [comment]
抱歉，我那时候点错了，点了“Contribute”，那时候不知道这个会提交我自己改的东西，因为我想弄个x86-64专用的，就改了文件还专门弄了一个分支，不让我的更改提交到主分支上，再次抱歉，耽误您时间了。

**Comment by ttimasdf** [comment]
没关系，我也手滑点错过，#1 就是我本来想提到上游的 PR，结果交给我自己了😂

**Comment by science2468** [comment]
> 没关系，我也手滑点错过，#1 就是我本来想提到上游的 PR，结果交给我自己了😂

我还是不会云编译，就放弃不用GitHub Actions编译了。luci-app-xray和语言包都是本地编译出来的。刚才看着邮件内容的翻译我都有点不知所措，我还以为您欣赏我的更改呢，幸亏看到了这个`[science2468](https://github.com/science2468) wants to merge 2 commits into [ttimasdf:main](https://github.com/ttimasdf/luci-app-xray) from [science2468:science2468-patch-1](https://github.com/science2468/luci-app-xray)` 我才知道是我自己提交上去的。😂

**Pull request closed without merging**
